name: Tamil Nadu Weather Bot

on:
  schedule:
    - cron: "30 7 * * *"   # 1:00 PM IST
  workflow_dispatch:       # allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run weather bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TOURISM_CHAT_ID: ${{ secrets.TOURISM_CHAT_ID }}
        run: python weatherbot.py
